### ISSUE TITLE
Question options

### ISSUE THREAD

**Issue by dragonxtek** [gpoore/text2qti#10]
Can you add the following options?

- Show one question at a time
- Blocking questions after they are

You're doing a very good job. Thanks so much for your input.

**Comment by gpoore** [comment]
I can look into adding some additional options. Can you clarify what the "blocking questions" amounts to? Is this not allowing someone to go back after a question has been answered?

**Comment by dragonxtek** [comment]
indeed that's what makes. Is a canvas option

**Comment by gpoore** [comment]
I've tried to add support for this, but it appears that Canvas ignores any settings for these options that are in a QTI file. So there doesn't appear to be a way to get this working.

I did add support for setting these options in the QTI file in the last commit, in case they work with systems besides Canvas or in case someone figures out a way to get them to work in the future.

Since there doesn't appear to be anything else that can be done, I'm closing this issue for now.

**Comment by gpoore** [comment]
After the bug fix from #18, these options are all working in Canvas.
