### ISSUE TITLE
Executable Binary?

### ISSUE THREAD

**Issue by vjanomolee** [gpoore/text2qti#27]
Hi. Would it be possible to have your text2qti   as a binary executable with some simple user interface? 
I'm fine with running commands and installing python- BUT the majority of teachers that need a QTI conversion workflow do not and will not. So I was hoping I could find a  text to qti converter that they could use as well.

Or maybe a way for me to hook my google apps script to run your python code?
https://youtu.be/t2Dzmcs0v-c      <------right now the commercial software Respondus is doing the conversion. Would be great to eliminate that step. 

Or anyone interested in forking this?

**Comment by gpoore** [comment]
An executable binary and graphical user interface would be a nice addition. I'm very busy with in-person teaching combined with hybrid/online in some cases to handle quarantined students, but I can try to work on this as I have time. If anyone comes across this issue and is interested in making an attempt, please comment before starting so that we can agree on a general approach and avoid duplicated effort.

I imagine an executable binary should be possible with something like [`py2exe`](https://www.py2exe.org/) or [Nuitka](http://nuitka.net/). I haven't personally used either. I believe `py2exe` is Windows-only, which is likely good enough at least to start with.

For a graphical user interface, [`tkinter`](https://docs.python.org/3/library/tkinter.html) would probably be sufficient, and has the advantage of being in the standard library. If someone wants to create a more sophisticated solution, I'm open to that, but ideally the first GUI should be easy to pack into a standalone binary.

**Comment by gpoore** [comment]
The latest version includes a graphical application, plus build scripts for a Windows standalone executable. Details plus a Windows .exe are at https://github.com/gpoore/text2qti/releases/tag/v0.5.0. I expect that the .exe may have issues with antivirus on some systems.
