### ISSUE TITLE
python scripts issues

### ISSUE THREAD

**Issue by dragonxtek** [gpoore/text2qti#3]
When I try to generate the qti file with python script I got an error:
![Selection_899](https://user-images.githubusercontent.com/10552658/81255016-93a6ce80-8ffa-11ea-8620-0791958dcfc2.png)
How I can fix it?

**Comment by dragonxtek** [comment]
I changed .python by .python3 and it generates the zip file, but when I load it to canvas the variables don't appear:
![Selection_900](https://user-images.githubusercontent.com/10552658/81255927-fd27dc80-8ffc-11ea-8684-bf29017b6d3d.png)
How can I fix it?

**Comment by gpoore** [comment]
That example uses Python 3.6+ (needs f-string), which is apparently available via `python3` rather than `python` on your system.

The example also uses LaTeX, which requires that a LaTeX render URL be set. Based on the screenshot, my guess is that the LaTeX URL hasn't been set or perhaps isn't working. If you aren't interested in using LaTeX, you can just change the example. Otherwise, you can set the URL in the config file `.text2qti.bespon` in the home directory. There are details about finding the URL under "Usage" in the README.

**Comment by dragonxtek** [comment]
Excelent! now it works
Thanks
