### ISSUE TITLE
Fill in the blank imports as essay

### ISSUE THREAD

**Issue by dlehman83** [gpoore/text2qti#36]
Hello, not sure if this is an issue with Schoology vs Canvas, but the fill in the black question imports as an essay question.  

I have copied and pasted most of your examples into a text file to check all the functionality with known working examples before I start trying my own.  

Keep up the good work, this looks to be an excellent tool.

**Comment by dlehman83** [comment]
Also to add Schoology does not import it as a QTI, but as a IMS.  It appears the only option I have to export is an imscc if you wanted to look at a file.  

Thanks,

**Comment by gpoore** [comment]
There's probably something that Schoology is doing different than Canvas...I just double checked, and Canvas still works fine for fill-in-the-blank. I don't use Schoology.

For import, QTI can be referred to as IMS QTI, so that may be what you're seeing in terms of import naming. It's also possible that Schoology is treating QTI as IMSCC for import, and somehow that works for most question types but not all. The [Schoology website](https://support.schoology.com/hc/en-us/articles/360014276193-How-do-I-import-QTI-content-into-Schoology-) says that QTI import should work, though, some I'm really not sure what is going on since just one question type isn't working.

**Comment by dlehman83** [comment]
I gave Schoology support a sample file last week because it would not import as a QTI.  They said it imported as a Common Cartridge IMS zip so use that as a work around.  
The Schoology import options are
Moodle (ZIP or MBZ)
Blackboard (ZIP)
Brainhoney (ZIP)
Common Cartridge (IMSCC or ZIP)
Standard ZIP File
QTI (ZIP)
Angel (ZIP)

Perhaps if the actual QTI import worked, it would work I'm not sure.  

I will open the case up with them again.  

How difficult would it be to output in a different format.  

I've not dug into the code too much, is the output processing part separate from the input.  

I'm not good in python, but I try to look at what you have done and change it to fit.

**Comment by gpoore** [comment]
If Schoology wont import text2qti QTI output, then there is probably some sort of mismatch. text2qti is based off of the QTI that Canvas uses, so it's possible there is something non-standard in that which is causing issues. Or Schoology may have something that isn't compatible in their import system.

It should be possible to add support for other formats besides QTI v1.2. The code isn't really optimized for supporting multiple output formats at present, but the input processing and the output processing are at least mostly separated. You would want to look at `qti.py` and the `xml_*.py` files. Basically, for another format, you need code that converts a `Quiz` object into an output file. This largely amounts to assembling a lot of XML templates, at least for the QTI case.

**Comment by dlehman83** [comment]
I escalated the ticket with Schoology and they wrote back saying the file was not QTI V1.2.  I also looked at the Canvas documentation and they say they only support V1.2 and V2.1.  Your file is using the V1.1 schema.  

Thanks,

**Comment by gpoore** [comment]
All of my XML is based off of Canvas QTI exports, which should be QTI v1.2. I suppose it's possible that the Canvas exports contain invalid XML.

There is a `<schemaversion>1.1.3</schemaversion>` in the manifest template (`xml_imsmanifest.py` around line 21).  However, I believe that refers to a packaging specification separate from QTI version (http://www.imsglobal.org/content/packaging/cpv1p1p3/imscp_infov1p1p3.html).

It looks like we may have a mismatch/bug between Canvas and Schoology regarding QTI specifications, or interpretation of the specifications. I'm happy to try to get text2qti working with systems other than Canvas. However, I only use Canvas and only have access to Canvas, and I don't have time to dig through all the details of the XML specifications to try to diagnose issues like this. Ideally, we need to find a simpler way to locate the issue. Can you create a quiz in Schoology with a fill-in-the-blank question and then export that to QTI, so that we can compare output? Or can you find a QTI v1.2 file with a fill-in-the-blank question that Schoology will import correctly? You could also try editing the text2qti output to use  `<schemaversion>1.2</schemaversion>` just to see what Schoology would do with that.

**Comment by dlehman83** [comment]
It looks like my only option for export is common cartridge.  
I did find that line and also noticed v1p2 on the other xml files.  

I'm going to setup a dev environment soon, but I've  not worked much with Python.  

This may be a simple question that doesn't belong here, but how can I run this program directly without setup.py.  
I was getting relative import errors and when I run setup.py I'm not sure where it copies it too.  I already had the compiled version installed.  

I plan to setup a fresh VM Monday so I know it is my changed version running vs the distrib version.  Any tips for quickly testing changes are welcome.

**Comment by gpoore** [comment]
A common way to test changes would be to create a virtual environment or (if using Anaconda) a conda environment, and do all work within that. The program does need to be installed via `setup.py` to function.

Sometimes I will just uninstall text2qti, go to the code directory, and use `python setup.py develop`, which installs the program but picks up any subsequent changes in the code. The exact develop installation command may need modification depending on your system...may need `python3` or `--user`. If you take that approach, then you'll want the equivalent of `python setup.py develop --uninstall` when you're done. Or just do all this within an environment to keep it isolated.

**Comment by dlehman83** [comment]
I have the dev environment setup, just changing the xml schema didn't work.  I've started comparing the output of text2qti and Schoology.  
Attached is an example quiz if you would like to have a look too.
[Test-Quizzes.zip](https://github.com/gpoore/text2qti/files/5725183/Test-Quizzes.zip)

**Comment by dlehman83** [comment]
I have fixed the imsmanifest file so it imports without the extra folders I was getting previously.  
The assessment meta file is not needed at all and now removed.  Some of its contents moved to imsmanifest.  
The last step is to actually get the fill in the blank questions to work.  I think I have found the key, but need to figure out just where to make the change.  

From the exported xml for fill in the blank
`<qtimetadatafield>
							<fieldlabel>
								cc_profile
							</fieldlabel>
							<fieldentry>
								cc.fib.v0p1
							</fieldentry>
						</qtimetadatafield>`

All questions seem to have the cc_profile and I have a list of values for different question types.  


Lines 145,158,and 179 of xml assessment contain this tag
`<render_fib>`
Is this anything to do with fill in the blank?
I'm not finding anything that specifically changes the xml for fill in the blank.  I think I'll have to add that.

**Comment by dlehman83** [comment]
I was able to remap your question types to those schoology is looking for.  
Fill in the blank now works, but there is no option for short answer.  I don't know if canvas treated them as the same or not, but text2qti did.  Schoology has two distinct question types.  
I have found a few more feature Schoology does not support, but I have basic functionality 

I'm ready to compile and deploy to my users.  

I have forked the project naming it text2cc.  

Thanks for the guidance.
