### ISSUE TITLE
example fails

### ISSUE THREAD

**Issue by bobkummerfeld** [gpoore/text2qti#6]
I tried the multiple answer example:
  1.  Which of the following are dinosaurs?
  [] Woolly mammoth
  [*] Tyrannosaurus rex
  [*] Triceratops
  [] Smilodon fatalis

but it fails with: 
  text2qti.err.Text2qtiError: In "t2.txt" on line 2:
  Syntax error; unexpected text, or incorrect indentation for a wrapped paragraph:
  "[] Woolly mammoth"

**Comment by gpoore** [comment]
I just added support for those types of questions a few hours ago, so it requires the development version off of GitHub, rather than the last release available via `pip` installation. You can follow the directions for installing the development version, or wait a day or two until the latest features are available via `pip`.

**Comment by bobkummerfeld** [comment]
Excellent - thanks for the rapid response!  I'll try the dev version.
