### ISSUE TITLE
Ambiguity between solutions and images

### ISSUE THREAD

**Issue by reidma** [gpoore/text2qti#61]
I think there may be an ambiguity in the format used for images and solutions. From what I can tell, both of them begin with ! at the start of the line. However, when I try to render an image that way, I get the error:

`Missing whitespace after "!"`

It's as if the code is looking for a solution, not an image, upon encountering '!'. For example, this md file produces the above error:

```
Quiz title: Testing 

1. Which of the following is the wavelength of this sine curve?

![graph](sine_curve1.png)
*a) 0.5
b) 1.0
c) 0.25
d) 0.75
e) 0.775


```

I think either the documentation could give a fuller example of how to include an image, or possibly a different character should be used to indicate the solution.

**Comment by gpoore** [comment]
You probably want to think about the plain text format for quizzes as a wrapper around Markdown. Each individual chunk of text (question, answer, feedback, etc.) is Markdown. But the outermost level of text (no indent) is the text2qti plain-text quiz format. So it is trying to interpret your image as a solution, because it isn't indented. Just indent the image to the same level as the question text:
```
Quiz title: Testing 

1. Which of the following is the wavelength of this sine curve?

   ![graph](sine_curve1.png)
*a) 0.5
b) 1.0
c) 0.25
d) 0.75
e) 0.775
```

**Comment by reidma** [comment]
Thanks! That works perfectly. I really appreciate your help, and your work developing this amazing tool!
