### ISSUE TITLE
Set question title

### ISSUE THREAD

**Issue by rzach** [gpoore/text2qti#9]
I mentioned this in #8 already: `text2qti` sets the title of every question to the same string, namely `Question`, e.g.,:
```
<item ident="text2qti_question_f80b14407f7c732e3b2a9c8ede5b5a5f7f48f671c7d2e2a3328eea79c2a7868d" title="Question">
```
The `title` attribute should be settable, and if not set it should be generated from the question description in some way, e.g., by taking the first 5 words or so from the description. To set it, one might write the title using a keyword and take the description from the next paragraph(s)? E.g.,:
```
1.  Title: Question title

    A question paragraph that is long enough to wrap onto a second line.
    The second line must be indented to match up with the start of the
    paragraph text on the first line.

    Another paragraph.
```

**Comment by gpoore** [comment]
I commented on titles in #8 before seeing this issue. The reason there isn't currently a way to set the title is because Canvas ignores titles. Can you try manually editing the XML title and importing in your system to verify that it will actually use titles? If some systems will actually use titles, I'll add title support. Before I realized Canvas wouldn't use titles, I was thinking about something like this:
```
Title: Question title
1.  A question paragraph that is long enough to wrap onto a second line.
    The second line must be indented to match up with the start of the
    paragraph text on the first line.

    Another paragraph.
```
That eliminates any potential for ambiguity in the question itself.

**Comment by rzach** [comment]
Can confirm Brightspace/D2L uses the title. Plain text only however just like quiz titles. Your proposed format for question titles works for me as long as you can distinguish between a question title and the last paragraph of the quiz description.
Once you're looking for question descriptions maybe it's not so much more work to implement other per-question settings like point value and difficulty?

**Comment by gpoore** [comment]
I'll add titles then, as well as other per-question settings.

There won't be issues with the question title and the last paragraph of the quiz description, because anything at the top level of the document that spans multiple lines is required to indent subsequent lines. That isn't ideal in some respects, and I should probably make the exact indentation requirements lest strict in some cases, but it does prevent ambiguity.

**Comment by rzach** [comment]
Ah that's good to know. The indentation requirement might make it harder to produce conforming input files. If having the title before the question makes it difficult to relax that, maybe putting title etc. after the question in the same space as the feedback might make more sense and would also be more consistent, e.g.,
```
1.  What is 2+3?
Title: Addition question
Points: 5
Difficulty: 2
... General question feedback.
+   Feedback for correct answer.
-   Feedback for incorrect answer. 
```

**Comment by gpoore** [comment]
I've added support for setting titles and points. Please let me know if titles work, since I can't check that through Canvas. Here's the format:
```
Title: An addition question
Points: 2
1.  What is 2+3?
... General question feedback.
+   Feedback for correct answer.
-   Feedback for incorrect answer.
a)  6
... Feedback for this particular answer.
b)  1
... Feedback for this particular answer.
*c) 5
... Feedback for this particular answer.
```
I haven't added difficulty. Canvas doesn't appear to support it. Do you know what that maps to in the XML? In the QTI spec (http://www.imsglobal.org/question/index.html#version1.2), the closest thing I could find was `qmd_levelofdifficulty`. If that's it, then something like
```
<qtimetadatafield>
  <fieldlabel>qmd_levelofdifficulty</fieldlabel>
  <fieldentry>basic</fieldentry>
</qtimetadatafield>
```
can be added under `<itemmetadata>` for each question.

**Comment by rzach** [comment]
Confirming that title and point value are set correctly in D2L.
I tried the `qmd_levelofdifficulty` field with both numeric and alpha values, but the D2L import doesn't seem to care about it.
So ok to close?

**Comment by gpoore** [comment]
I'll close this, and if we ever figure out how to handle some of these other properties I'll be happy to add that later.
